#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
init_workspace.sh: generate/apply a SmartWorkers-style agent workspace skeleton

Usage:
  # From the skill folder (recommended):
  bash scripts/init_workspace.sh [options]

  # From the repo root (alternative):
  bash skills/general/workspace-setup/scripts/init_workspace.sh [options]

Options:
  --repo PATH         Repo root (default: .)
  --apply             Write into repo root (default: generate into logs/)
  --node VERSION      Node version for mise (default: 24)
  --python VERSION    Python version for mise (default: 3.14)
  --bun VERSION       Bun version for mise (default: latest)
  --uv VERSION        uv version for mise (default: latest)
  --install           Run `mise install`, `npm i skills -g`, and install `skill-creator` for Codex (requires mise)
  --uv-sync           Run `uv venv --seed` then `uv sync` (requires uv)
  -h, --help          Show help

Notes:
  - Without --apply, files are written to logs/workspace-setup/ for review.
  - With --apply, existing files are never overwritten.
  - Generates the baseline workspace skeleton:
    - repo root: AGENTS.md (workspace policy)
    - logs/: logs/AGENTS.md (scratch rules)
    - artifacts/: artifacts/AGENTS.md (deliverables rules)
    - README.md, WORKFLOW.md, .gitignore, .ignore, workers.example.jsonc
    - .mise.toml, package.json, pyproject.toml
  - With --install, the script also installs the `skills` CLI globally and adds `skill-creator` to Codex for this workspace.
  - With --apply, this script refuses to run if the repo already has an AGENTS.md. Create a new empty folder for a new workspace.
EOF
}

repo="."
node_version="24"
python_version="3.14"
bun_version="latest"
uv_version="latest"
skill_creator_url="https://github.com/anthropics/skills/tree/main/skills/skill-creator"
apply="false"
do_install="false"
do_uv_sync="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) repo="${2:-}"; shift 2 ;;
    --node) node_version="${2:-}"; shift 2 ;;
    --python) python_version="${2:-}"; shift 2 ;;
    --bun) bun_version="${2:-}"; shift 2 ;;
    --uv) uv_version="${2:-}"; shift 2 ;;
    --apply) apply="true"; shift ;;
    --install) do_install="true"; shift ;;
    --uv-sync) do_uv_sync="true"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

repo="$(cd "$repo" && pwd)"
if [[ ! -d "$repo" ]]; then
  echo "Repo path does not exist: $repo" >&2
  exit 1
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
assets_dir="$script_dir/../assets/templates"
skill_dir="$(cd -- "$script_dir/.." && pwd)"

if [[ ! -d "$assets_dir" ]]; then
  echo "Missing assets templates directory: $assets_dir" >&2
  exit 1
fi

sanitize_project_name() {
  local raw="$1"
  raw="$(echo "$raw" | tr '[:upper:]' '[:lower:]')"
  raw="$(echo "$raw" | tr ' ' '-')"
  raw="$(echo "$raw" | tr -cs 'a-z0-9-' '-')"
  raw="$(echo "$raw" | sed -E 's/^-+//; s/-+$//; s/-{2,}/-/g')"
  if [[ -z "$raw" ]]; then
    raw="workspace"
  fi
  echo "$raw"
}

project_name="$(sanitize_project_name "$(basename "$repo")")"

render_template() {
  local template_path="$1"
  local node_v="$2"
  local python_v="$3"
  local bun_v="$4"
  local uv_v="$5"
  local proj="$6"

  sed \
    -e "s/{{NODE_VERSION}}/${node_v}/g" \
    -e "s/{{PYTHON_VERSION}}/${python_v}/g" \
    -e "s/{{BUN_VERSION}}/${bun_v}/g" \
    -e "s/{{UV_VERSION}}/${uv_v}/g" \
    -e "s/{{PROJECT_NAME}}/${proj}/g" \
    "$template_path"
}

generate_workspace_root_agents_md() {
  render_template "$assets_dir/AGENTS.md.tmpl" \
    "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name"
}

generate_folder_agents_md() {
  local template_name="$1"
  render_template "$assets_dir/$template_name" \
    "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name"
}

generate_gitignore() {
  cat <<'EOF'
# Generated by skills/general/workspace-setup/scripts/init_workspace.sh
#
# This file is a pragmatic merge of:
# - the repo's existing .gitignore (if present)
# - common patterns from https://github.com/github/gitignore (see recommended block below)
EOF

  echo

  if [[ -f "$repo/.gitignore" ]]; then
    echo "# --- Existing repo .gitignore (as reference) ---"
    cat "$repo/.gitignore"
    echo
  fi

  cat "$assets_dir/gitignore.recommended"
}

generate_ignore_for_workdirs() {
  cat <<'EOF'
# Generated by skills/general/workspace-setup/scripts/init_workspace.sh
#
# Codex (and some tooling) uses ignore files to decide which files are visible/searchable.
# This workspace's `.gitignore` may intentionally ignore paths the agent still needs to
# recognize (e.g. `workers.jsonc`, `logs/`, `artifacts/`). This `.ignore` file re-includes
# the essential working paths for agent runs and deliverables.
#
# NOTE: Visibility is not permission — avoid reading secrets unless the task requires it.
EOF

  echo
  cat <<'EOF'
!workers.jsonc
!logs/
!logs/**
!artifacts/
!artifacts/**
EOF
}

if [[ "$do_install" == "true" || "$do_uv_sync" == "true" ]] && [[ "$apply" != "true" ]]; then
  echo "--install/--uv-sync require --apply (they modify the repo root)." >&2
  exit 2
fi

if [[ "$apply" == "true" ]]; then
  if [[ -f "$repo/AGENTS.md" ]]; then
    echo "Refusing to apply workspace setup: AGENTS.md already exists at $repo/AGENTS.md" >&2
    echo "This skill is for initializing a new workspace. Create a new empty folder and run again with --repo <new-folder>." >&2
    exit 1
  fi
  out_dir="$repo"
else
  out_dir="$repo/logs/workspace-setup"
fi

mkdir -p "$out_dir"

gitignore_target="$out_dir/.gitignore"
ignore_target="$out_dir/.ignore"
workers_example_target="$out_dir/workers.example.jsonc"
readme_target="$out_dir/README.md"
workflow_target="$out_dir/WORKFLOW.md"
mise_toml_target="$out_dir/.mise.toml"
package_json_target="$out_dir/package.json"
pyproject_target="$out_dir/pyproject.toml"

if [[ "$apply" == "true" ]]; then
  workspace_agents_target="$repo/AGENTS.md"
  temp_agents_target="$repo/logs/AGENTS.md"
  artifacts_agents_target="$repo/artifacts/AGENTS.md"
else
  workspace_agents_target="$out_dir/AGENTS.md"
  temp_agents_target="$out_dir/logs.AGENTS.md"
  artifacts_agents_target="$out_dir/artifacts.AGENTS.md"
fi

write_if_missing() {
  local target="$1"
  local label="$2"
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp"
  if [[ -f "$target" ]]; then
    echo "Skip (already exists): $label -> $target"
    rm -f "$tmp"
    return 0
  fi
  mv "$tmp" "$target"
  echo "Wrote: $label -> $target"
}

generate_gitignore | write_if_missing "$gitignore_target" ".gitignore"

generate_ignore_for_workdirs | write_if_missing "$ignore_target" ".ignore"

render_template "$assets_dir/workers.example.jsonc.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$workers_example_target" "workers.example.jsonc"

render_template "$assets_dir/README.md.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$readme_target" "README.md"

render_template "$assets_dir/WORKFLOW.md.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$workflow_target" "WORKFLOW.md"

render_template "$assets_dir/.mise.toml.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$mise_toml_target" ".mise.toml"

render_template "$assets_dir/package.json.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$package_json_target" "package.json"

render_template "$assets_dir/pyproject.toml.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$pyproject_target" "pyproject.toml"

if [[ "$apply" == "true" ]]; then
  mkdir -p "$repo/logs" "$repo/artifacts"
fi

generate_workspace_root_agents_md | write_if_missing "$workspace_agents_target" "AGENTS.md"

generate_folder_agents_md "logs.AGENTS.md.tmpl" | write_if_missing "$temp_agents_target" "logs/AGENTS.md"
generate_folder_agents_md "artifacts.AGENTS.md.tmpl" | write_if_missing "$artifacts_agents_target" "artifacts/AGENTS.md"

if [[ "$apply" == "false" ]]; then
  echo
  echo "Generated files for review in: $out_dir"
  echo "To apply to repo root:"
  echo "  - From the skill folder: (cd \"$skill_dir\" && bash scripts/init_workspace.sh --apply)"
  echo "  - From the repo root: bash skills/general/workspace-setup/scripts/init_workspace.sh --apply"
  exit 0
fi

echo
echo "Applied (without overwriting existing files) in repo root: $repo"

if [[ "$do_install" == "true" ]]; then
  if ! command -v mise >/dev/null 2>&1; then
    echo "mise not found. Install/activate mise first: https://mise.jdx.dev/getting-started.html" >&2
    exit 1
  fi
  (cd "$repo" && mise install)
  (cd "$repo" && mise exec -- npm i skills -g)
  (cd "$repo" && mise exec -- npx skills add -a codex -y "$skill_creator_url")
fi

if [[ "$do_uv_sync" == "true" ]]; then
  if command -v uv >/dev/null 2>&1; then
    (cd "$repo" && uv venv --seed)
    (cd "$repo" && uv sync)
  elif command -v mise >/dev/null 2>&1; then
    if ! (cd "$repo" && mise exec -- uv --version >/dev/null 2>&1); then
      echo "uv not available via mise. Run with --install first, or install uv, then re-run with --uv-sync." >&2
      exit 1
    fi
    (cd "$repo" && mise exec -- uv venv --seed)
    (cd "$repo" && mise exec -- uv sync)
  else
    echo "uv not found. Install uv (or install/activate mise), then re-run with --uv-sync." >&2
    exit 1
  fi
fi
