#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
init_workspace.sh: generate/apply mise + uv workspace bootstrap files

Usage:
  # From the skill folder (recommended):
  bash scripts/init_workspace.sh [options]

  # From the repo root (alternative):
  bash skills/general/workspace-setup/scripts/init_workspace.sh [options]

Options:
  --repo PATH         Repo root (default: .)
  --node VERSION      Node version for mise (default: 24)
  --python VERSION    Python version for mise (default: 3.14)
  --bun VERSION       Bun version for mise (default: latest)
  --uv VERSION        uv version for mise (default: latest)
  --apply             Write into repo root (default: generate into temp/)
  --install           Run `mise install` after applying (requires mise)
  --uv-sync           Run `uv venv --seed` then `uv sync` after install/apply (requires uv)
  -h, --help          Show help

Notes:
  - Without --apply, files are written to temp/workspace-setup/ for review.
  - With --apply, existing .mise.toml / .gitignore / .ignore / package.json / pyproject.toml are never overwritten.
EOF
}

repo="."
node_version="24"
python_version="3.14"
bun_version="latest"
uv_version="latest"
apply="false"
do_install="false"
do_uv_sync="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) repo="${2:-}"; shift 2 ;;
    --node) node_version="${2:-}"; shift 2 ;;
    --python) python_version="${2:-}"; shift 2 ;;
    --bun) bun_version="${2:-}"; shift 2 ;;
    --uv) uv_version="${2:-}"; shift 2 ;;
    --apply) apply="true"; shift ;;
    --install) do_install="true"; shift ;;
    --uv-sync) do_uv_sync="true"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

repo="$(cd "$repo" && pwd)"
if [[ ! -d "$repo" ]]; then
  echo "Repo path does not exist: $repo" >&2
  exit 1
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
assets_dir="$script_dir/../assets/templates"
skill_dir="$(cd -- "$script_dir/.." && pwd)"

if [[ ! -d "$assets_dir" ]]; then
  echo "Missing assets templates directory: $assets_dir" >&2
  exit 1
fi

sanitize_project_name() {
  local raw="$1"
  raw="$(echo "$raw" | tr '[:upper:]' '[:lower:]')"
  raw="$(echo "$raw" | tr ' ' '-')"
  raw="$(echo "$raw" | tr -cs 'a-z0-9-' '-')"
  raw="$(echo "$raw" | sed -E 's/^-+//; s/-+$//; s/-{2,}/-/g')"
  if [[ -z "$raw" ]]; then
    raw="workspace"
  fi
  echo "$raw"
}

project_name="$(sanitize_project_name "$(basename "$repo")")"

render_template() {
  local template_path="$1"
  local node_v="$2"
  local python_v="$3"
  local bun_v="$4"
  local uv_v="$5"
  local proj="$6"

  sed \
    -e "s/{{NODE_VERSION}}/${node_v}/g" \
    -e "s/{{PYTHON_VERSION}}/${python_v}/g" \
    -e "s/{{BUN_VERSION}}/${bun_v}/g" \
    -e "s/{{UV_VERSION}}/${uv_v}/g" \
    -e "s/{{PROJECT_NAME}}/${proj}/g" \
    "$template_path"
}

generate_gitignore() {
  cat <<'EOF'
# Generated by skills/general/workspace-setup/scripts/init_workspace.sh
#
# This file is a pragmatic merge of:
# - the repo's existing .gitignore (if present)
# - common patterns from https://github.com/github/gitignore (see recommended block below)
EOF

  echo

  if [[ -f "$repo/.gitignore" ]]; then
    echo "# --- Existing repo .gitignore (as reference) ---"
    cat "$repo/.gitignore"
    echo
  fi

  cat "$assets_dir/gitignore.recommended"
}

generate_ignore_for_workdirs() {
  cat <<'EOF'
  # Generated by skills/general/workspace-setup/scripts/init_workspace.sh
  #
  # Codex (and some tooling) uses ignore files to decide which files are visible/searchable.
  # This workspace's `.gitignore` may intentionally ignore paths the agent still needs to
  # recognize (e.g. `temp/`, `artifacts/`). This `.ignore` file re-includes *only* the
  # working folders used for agent runs and deliverables (not all of `.gitignore`).
  #
  # NOTE: Visibility is not permission — avoid reading secrets unless the task requires it.
EOF

  echo
  cat <<'EOF'
!temp/
!temp/**
!artifacts/
!artifacts/**
EOF
}

if [[ "$apply" == "true" ]]; then
  out_dir="$repo"
else
  out_dir="$repo/temp/workspace-setup"
fi

mkdir -p "$out_dir"

mise_toml_target="$out_dir/.mise.toml"
gitignore_target="$out_dir/.gitignore"
ignore_target="$out_dir/.ignore"
package_json_target="$out_dir/package.json"
pyproject_target="$out_dir/pyproject.toml"

write_if_missing() {
  local target="$1"
  local label="$2"
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp"
  if [[ -f "$target" ]]; then
    echo "Skip (already exists): $label -> $target"
    rm -f "$tmp"
    return 0
  fi
  mv "$tmp" "$target"
  echo "Wrote: $label -> $target"
}

render_template "$assets_dir/.mise.toml.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$mise_toml_target" ".mise.toml"

generate_gitignore | write_if_missing "$gitignore_target" ".gitignore"

generate_ignore_for_workdirs | write_if_missing "$ignore_target" ".ignore"

render_template "$assets_dir/package.json.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$package_json_target" "package.json"

render_template "$assets_dir/pyproject.toml.tmpl" \
  "$node_version" "$python_version" "$bun_version" "$uv_version" "$project_name" \
  | write_if_missing "$pyproject_target" "pyproject.toml"

if [[ "$apply" == "false" ]]; then
  echo
  echo "Generated files for review in: $out_dir"
  echo "To apply to repo root:"
  echo "  - From the skill folder: (cd \"$skill_dir\" && bash scripts/init_workspace.sh --apply)"
  echo "  - From the repo root: bash skills/general/workspace-setup/scripts/init_workspace.sh --apply"
  exit 0
fi

echo
echo "Applied (without overwriting existing files) in repo root: $repo"

if [[ "$do_install" == "true" ]]; then
  if ! command -v mise >/dev/null 2>&1; then
    echo "mise not found. Install/activate mise first: https://mise.jdx.dev/getting-started.html" >&2
    exit 1
  fi
  (cd "$repo" && mise install)
fi

if [[ "$do_uv_sync" == "true" ]]; then
  if command -v uv >/dev/null 2>&1; then
    (cd "$repo" && uv venv --seed)
    (cd "$repo" && uv sync)
  elif command -v mise >/dev/null 2>&1; then
    if ! (cd "$repo" && mise exec -- uv --version >/dev/null 2>&1); then
      echo "uv not available via mise. Run with --install first, or install uv, then re-run with --uv-sync." >&2
      exit 1
    fi
    (cd "$repo" && mise exec -- uv venv --seed)
    (cd "$repo" && mise exec -- uv sync)
  else
    echo "uv not found. Install uv (or install/activate mise), then re-run with --uv-sync." >&2
    exit 1
  fi
fi
